openapi: 3.0.1
info:
  title: Event Ledger Services API
  description: API to get ECPD insights with API key security.
  version: 1.0.0
servers:
  - url: https://oa-dev2.ebiz.verizon.com/eventledger-services
    description: Development Server
paths:
  /ecpd/insights/search:
    post:
      summary: Get ECPD Insights
      description: Endpoint to search ECPD insights using `ecpdId`, `resolvedStatuslimit`, `insightCategory`, and `insightName`.
      operationId: getEcpdInsights
      requestBody:
        description: JSON payload for searching ECPD insights
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                serviceHeader:
                  type: object
                  properties:
                    clientId:
                      type: string
                      example: MyBIZ
                    clientTransactionId:
                      type: string
                      example: "65656-778787-376676"
                    serviceName:
                      type: string
                      example: getEcpdInsights
                serviceRequest:
                  type: object
                  properties:
                    ecpdId:
                      type: string
                      example: "2369701"
                    resolvedStatuslimit:
                      type: string
                      example: "40"  # Represents the number of hours
                    insightCategory:
                      type: array
                      items:
                        type: string
                        example: "VBGNxOutage"
                    insightName:
                      type: array
                      items:
                        type: string
                        example: "ecpdOutage"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestinfo:
                    type: object
                    properties:
                      ecpdId:
                        type: string
                        example: "2369781"
                      insightCategory:
                        type: array
                        items:
                          type: string
                          example: "VBGNxOutage"
                      resolvedStatuslimit:
                        type: string
                        example: "40"
                      insightName:
                        type: array
                        items:
                          type: string
                          example: "ecpdOutage"
                  ecpdInsights:
                    type: array
                    items:
                      type: object
                      properties:
                        category:
                          type: string
                          example: "VBGNxOutage"
                        name:
                          type: string
                          example: "ecpdOutage"
                        value:
                          type: array
                          items:
                            type: object
                            properties:
                              outageId:
                                type: string
                                example: "311423"
                              milestoneName:
                                type: string
                                example: "Engineers diagnosing the issue"
                              outageStartDatetime:
                                type: string
                                format: date-time
                                example: "2024-12-16T11:35:00.000Z"
                              outageEstimatedDatetime:
                                type: string
                                format: date-time
                                example: "2024-12-24T11:48:00.000Z"
                              resolutionTime:
                                type: string
                                example: "1282412051100000"
                              isMobility:
                                type: string
                                example: ""
                              isGenSubscribed:
                                type: string
                                example: ""
                              multiCityImpact:
                                type: boolean
                                example: false
                              city:
                                type: string
                                example: "Eld Bridge"
                              state:
                                type: string
                                example: "NJ"
                              eventType:
                                type: string
                                example: "Ran"
                              eventTs:
                                type: string
                                format: date-time
                                example: "2024-12-24T11:48:00.000Z"
                  status:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "00000"
                      message:
                        type: string
                        example: "SUCCESS"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Invalid request payload.
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Server error occurred.
      security:
        - apiKeyAuth: []
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: apikey
